### ISSUE TITLE
dashboard_app.DashboardWidgetLastUpdate.last_update: (fields.E160) The options auto_now, auto_now_add, and default are mutually exclusive. Only one of these options may be present.

### ISSUE THREAD

**Issue by shubham2892** [bitmazk/django-dashboard-app#2]
This is the issue I am facing while upgrading to Django 1.8.

**Comment by mbrochh** [comment]
@shubham2892 by the way, I never really used this app in production. I discovered influxdb and grafana when I was halfway through this and gave up on this app. I'm not sure, but you might be wasting your time on this one.

**Comment by devjon** [comment]
@mbrochh : Yeah, they are really cool. Moving on to grafana.
